// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ObjectPlugin","status":true,"description":"","parameters":{}},
{"name":"MessageItemInfo","status":true,"description":"Allows to show Item Information in the Message Windows","parameters":{}},
{"name":"EnemyHPByLevel","status":true,"description":"Added dem Gegner zusätzliche HP hinzu, je nachdem wie hoch dieser ist","parameters":{"Actor Id":"5","Factor":"1.3"}}
];
